[programs.localnet]
gem_bank = "EnJJ3BxBE3oZZMvBVqg8K9bSnGb7VREpPbZYuHEWLg1n"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/ilmoi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

#[test]
#startup_wait = 100000