[programs.localnet]
gem_bank = "DP12bYzGKK3eZYKe3PJjuwnkiRjjTMMCttpivezXLtmo"
gem_farm = "5f8w4vbj1CkUBtiZa5k18AjP4R6Qi63pkruDD5xRZwVT"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/ilmoi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

#[test]
#startup_wait = 100000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/programs/metaplex_token_metadata.so"